### ISSUE TITLE
Corrections and suggestions

### ISSUE THREAD

**Issue by sharicov** [exah-io/minimal-arch-linux#3]
1. Please replace wictl with iwctl (typo).
2. Also please add target disk in install script as variable, so it is possible to install to sda for example.
3. Suggest to shorten the download links with link shortner (like bitly) to avoid long typing when doing wget download.
Otherwise great job!
P.S tested in VMware and on several laptops (installed to USB). VMWare and Intel graphics laptop work fine. Nvidia graphics laptop freezes on boot. For VMWare in order to boot (UEFI) added firmware = "efi" in the .vmx file.

**Comment by gjpin** [comment]
Sorry for the late feedback, as I didn't notice it before! Thanks a lot for the feedback. 

I'll improve accordingly.  Nvidia GPUs are not supported by these scripts though, as I don't have one and there are complications with KDE wayland.

Thanks
