### ISSUE TITLE
Errors in arch

### ISSUE THREAD

**Issue by sharicov** [exah-io/minimal-arch-linux#4]
Installed with yaourt (https://cloudcone.com/docs/article/install-packages-in-arch-linux-from-aur/)
installed dependencies:
 sudo pacman -Syu --needed python python-gobject python-yaml python-pyzmq python-humanize gtk3 partclone zeromq rustup git pigz polkit lz4 zstd

Getting following error:
sudo apart-gtk
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/bin/apart-gtk", line 8, in <module>
    from main import CloneBody
  File "/usr/lib/apart-gtk/src/main.py", line 3, in <module>
    from cloneentry import CloneToImageEntry
  File "/usr/lib/apart-gtk/src/cloneentry.py", line 3, in <module>
    from partinfo import PartitionInfo
  File "/usr/lib/apart-gtk/src/partinfo.py", line 3, in <module>
    import humanize
  File "/usr/lib/python3.8/site-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by gjpin** [comment]
I'm not familiar with apart-gtk, sorry.

But, if you used the scripts, why did you install yaourt? The scripts already install yay.

**Comment by sharicov** [comment]
apart-gtk is gui for part lone to create disk backups https://github.com/alexheretic/apart-gtk
I have installed yaourt because I am new to arch and didn't figure out yet how aur repository is used. Thanks for the hint.
