### ISSUE TITLE
clarification GPU

### ISSUE THREAD

**Issue by Isetnt2** [exah-io/minimal-arch-linux#6]
> GPU: AMDGPU - only if CPU vendor is AMD (this combination is hard-coded. For now, base script checks for CPU vendor and if it's AMD, then it'll also install required drivers for AMD GPU)

Does this mean that it only installs AMDGPU if both CPU and GPU is AMD or that if you use an AMD based CPU you need an AMD based GPU or vice versa?

I have an Intel CPU and a r9 290x so some clarification would be great.

**Comment by gjpin** [comment]
sorry for the delay. the scripts now check for the actual GPU vendor instead of the hardcoded combination.
